//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteSorti))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.MsgTrait> InfoMsgTraitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.MsgTrait> InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnGabaritSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA1_SaisAvisConf_cpo.Gabarit.Pa" +
        "ram")]
    [System.SerializableAttribute()]
    public partial class ObtnGabaritSorti : RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ParamSorti {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] GabaritPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GabaritPDF {
            get {
                return this.GabaritPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.GabaritPDFField, value) != true)) {
                    this.GabaritPDFField = value;
                    this.RaisePropertyChanged("GabaritPDF");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class ExceptionRamqIntrn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string PileAppelField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.InnerExceptionRamq> InnerExceptionField;
        
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PileAppel {
            get {
                return this.PileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.PileAppelField, value) != true)) {
                    this.PileAppelField = value;
                    this.RaisePropertyChanged("PileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.InnerExceptionRamq> InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class InnerExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InnerMessageField;
        
        private string InnerPileAppelField;
        
        private string InnerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerMessage {
            get {
                return this.InnerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerMessageField, value) != true)) {
                    this.InnerMessageField = value;
                    this.RaisePropertyChanged("InnerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerPileAppel {
            get {
                return this.InnerPileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerPileAppelField, value) != true)) {
                    this.InnerPileAppelField = value;
                    this.RaisePropertyChanged("InnerPileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerType {
            get {
                return this.InnerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerTypeField, value) != true)) {
                    this.InnerTypeField = value;
                    this.RaisePropertyChanged("InnerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnGabaritEntre", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA1_SaisAvisConf_cpo.Gabarit.Pa" +
        "ram")]
    [System.SerializableAttribute()]
    public partial class ObtnGabaritEntre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDebutPrevueAvisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerritoireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.TypeActionAvisConformite TypeActionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDebutPrevueAvis {
            get {
                return this.DateDebutPrevueAvisField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDebutPrevueAvisField, value) != true)) {
                    this.DateDebutPrevueAvisField = value;
                    this.RaisePropertyChanged("DateDebutPrevueAvis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationMedecin {
            get {
                return this.IdentificationMedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationMedecinField, value) != true)) {
                    this.IdentificationMedecinField = value;
                    this.RaisePropertyChanged("IdentificationMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageConfirmation {
            get {
                return this.MessageConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageConfirmationField, value) != true)) {
                    this.MessageConfirmationField = value;
                    this.RaisePropertyChanged("MessageConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Territoire {
            get {
                return this.TerritoireField;
            }
            set {
                if ((object.ReferenceEquals(this.TerritoireField, value) != true)) {
                    this.TerritoireField = value;
                    this.RaisePropertyChanged("Territoire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.TypeActionAvisConformite TypeAction {
            get {
                return this.TypeActionField;
            }
            set {
                if ((this.TypeActionField.Equals(value) != true)) {
                    this.TypeActionField = value;
                    this.RaisePropertyChanged("TypeAction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeActionAvisConformite", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA1_SaisAvisConf_cpo.Gabarit")]
    public enum TypeActionAvisConformite : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Autre = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enregistre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transmis = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supprime = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modifier = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annule = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoque = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reporte = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PLA1_SaisAvisConf_svc/1", ConfigurationName="svcSaisAvisConf.IServSaisAvisConf", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServSaisAvisConf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerAvisConformiteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerAvisConformiteExceptionRamq" +
            "IntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteSorti CreerAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerAvisConformiteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteSorti> CreerAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerStatutAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerStatutAvisConformiteRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerStatutAvisConformiteExcepti" +
            "onRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteSorti CreerStatutAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerStatutAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/CreerStatutAvisConformiteRespons" +
            "e")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteSorti> CreerStatutAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierAvisConformiteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierAvisConformiteExceptionR" +
            "amqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteSorti ModifierAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierAvisConformiteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteSorti> ModifierAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirLesAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirLesAvisConformiteResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirLesAvisConformiteExceptio" +
            "nRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteSorti ObtenirLesAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirLesAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirLesAvisConformiteResponse" +
            "")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteSorti> ObtenirLesAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierPeriodeAvis", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierPeriodeAvisResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierPeriodeAvisExceptionRamq" +
            "IntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisSorti ModifierPeriodeAvis(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierPeriodeAvis", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierPeriodeAvisResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisSorti> ModifierPeriodeAvisAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/TraiterAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/TraiterAvisConformiteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/TraiterAvisConformiteExceptionRa" +
            "mqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteSorti TraiterAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/TraiterAvisConformite", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/TraiterAvisConformiteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteSorti> TraiterAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ValidationAvisDerogationEnCours", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ValidationAvisDerogationEnCoursR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ValidationAvisDerogationEnCoursE" +
            "xceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursSorti ValidationAvisDerogationEnCours(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ValidationAvisDerogationEnCours", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ValidationAvisDerogationEnCoursR" +
            "esponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursSorti> ValidationAvisDerogationEnCoursAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierStatutEngagement", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierStatutEngagementResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierStatutEngagementExceptio" +
            "nRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementSorti ModifierStatutEngagement(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierStatutEngagement", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ModifierStatutEngagementResponse" +
            "")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementSorti> ModifierStatutEngagementAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirGabaritConfirmation", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirGabaritConfirmationRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirGabaritConfirmationExcept" +
            "ionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritSorti ObtenirGabaritConfirmation(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritEntre parametreEntre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirGabaritConfirmation", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServSaisAvisConf/ObtenirGabaritConfirmationRespon" +
            "se")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritSorti> ObtenirGabaritConfirmationAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritEntre parametreEntre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServSaisAvisConfChannel : RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.IServSaisAvisConf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServSaisAvisConfClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.IServSaisAvisConf>, RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.IServSaisAvisConf {
        
        public ServSaisAvisConfClient() {
        }
        
        public ServSaisAvisConfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServSaisAvisConfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServSaisAvisConfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServSaisAvisConfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteSorti CreerAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteEntre intrant) {
            return base.Channel.CreerAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteSorti> CreerAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerAvisConformiteEntre intrant) {
            return base.Channel.CreerAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteSorti CreerStatutAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteEntre intrant) {
            return base.Channel.CreerStatutAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteSorti> CreerStatutAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.CreerStatutAvisConformiteEntre intrant) {
            return base.Channel.CreerStatutAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteSorti ModifierAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteEntre intrant) {
            return base.Channel.ModifierAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteSorti> ModifierAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierAvisConformiteEntre intrant) {
            return base.Channel.ModifierAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteSorti ObtenirLesAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteEntre intrant) {
            return base.Channel.ObtenirLesAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteSorti> ObtenirLesAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ObtenirLesAvisConformiteEntre intrant) {
            return base.Channel.ObtenirLesAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisSorti ModifierPeriodeAvis(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisEntre intrant) {
            return base.Channel.ModifierPeriodeAvis(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisSorti> ModifierPeriodeAvisAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierPeriodeAvisEntre intrant) {
            return base.Channel.ModifierPeriodeAvisAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteSorti TraiterAvisConformite(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteEntre intrant) {
            return base.Channel.TraiterAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteSorti> TraiterAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.TraiterAvisConformiteEntre intrant) {
            return base.Channel.TraiterAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursSorti ValidationAvisDerogationEnCours(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursEntre intrant) {
            return base.Channel.ValidationAvisDerogationEnCours(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursSorti> ValidationAvisDerogationEnCoursAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ValiderAvisDerogationEnCoursEntre intrant) {
            return base.Channel.ValidationAvisDerogationEnCoursAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementSorti ModifierStatutEngagement(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementEntre intrant) {
            return base.Channel.ModifierStatutEngagement(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementSorti> ModifierStatutEngagementAsync(RAMQ.PRE.PRE_Entites_cpo.AvisConformite.Parametre.ModifierStatutEngagementEntre intrant) {
            return base.Channel.ModifierStatutEngagementAsync(intrant);
        }
        
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritSorti ObtenirGabaritConfirmation(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmation(parametreEntre);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritSorti> ObtenirGabaritConfirmationAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisAvisConf.ObtnGabaritEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmationAsync(parametreEntre);
        }
    }
}
