//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf {
    using System.Runtime.Serialization;
    using System;
    
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.MsgTrait> InfoMsgTraitField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.MsgTrait> InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValiderProfessionnelSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Par" +
        "ametres")]
    [System.SerializableAttribute()]
    public partial class ValiderProfessionnelSorti : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ParamSorti {
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReductionRemunerationSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Par" +
        "ametres")]
    [System.SerializableAttribute()]
    public partial class ReductionRemunerationSorti : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ParamSorti {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemuneration> ReductionRemunerationsField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemuneration> ReductionRemunerations {
            get {
                return this.ReductionRemunerationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReductionRemunerationsField, value) != true)) {
                    this.ReductionRemunerationsField = value;
                    this.RaisePropertyChanged("ReductionRemunerations");
                }
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenirPourcentageMaximumSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Par" +
        "ametres")]
    [System.SerializableAttribute()]
    public partial class ObtenirPourcentageMaximumSorti : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ParamSorti {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PourcentageMaximumField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PourcentageMaximum {
            get {
                return this.PourcentageMaximumField;
            }
            set {
                if ((this.PourcentageMaximumField.Equals(value) != true)) {
                    this.PourcentageMaximumField = value;
                    this.RaisePropertyChanged("PourcentageMaximum");
                }
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReductionRemuneration", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Ent" +
        "ites")]
    [System.SerializableAttribute()]
    public partial class ReductionRemuneration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstExemptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroSequentielReductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaisonExemptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaisonReductionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeReductionField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((this.DateDebutField.Equals(value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFin {
            get {
                return this.DateFinField;
            }
            set {
                if ((this.DateFinField.Equals(value) != true)) {
                    this.DateFinField = value;
                    this.RaisePropertyChanged("DateFin");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstExemption {
            get {
                return this.EstExemptionField;
            }
            set {
                if ((this.EstExemptionField.Equals(value) != true)) {
                    this.EstExemptionField = value;
                    this.RaisePropertyChanged("EstExemption");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroSequentielReduction {
            get {
                return this.NumeroSequentielReductionField;
            }
            set {
                if ((this.NumeroSequentielReductionField.Equals(value) != true)) {
                    this.NumeroSequentielReductionField = value;
                    this.RaisePropertyChanged("NumeroSequentielReduction");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RaisonExemption {
            get {
                return this.RaisonExemptionField;
            }
            set {
                if ((object.ReferenceEquals(this.RaisonExemptionField, value) != true)) {
                    this.RaisonExemptionField = value;
                    this.RaisePropertyChanged("RaisonExemption");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RaisonReduction {
            get {
                return this.RaisonReductionField;
            }
            set {
                if ((object.ReferenceEquals(this.RaisonReductionField, value) != true)) {
                    this.RaisonReductionField = value;
                    this.RaisePropertyChanged("RaisonReduction");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeReduction {
            get {
                return this.TypeReductionField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeReductionField, value) != true)) {
                    this.TypeReductionField = value;
                    this.RaisePropertyChanged("TypeReduction");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class ExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strMessageField;
        
        private string MessageField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strMessage {
            get {
                return this.strMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.strMessageField, value) != true)) {
                    this.strMessageField = value;
                    this.RaisePropertyChanged("strMessage");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValiderProfessionnelEntre", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Par" +
        "ametres")]
    [System.SerializableAttribute()]
    public partial class ValiderProfessionnelEntre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDecesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DatePremiereSpecialiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroClasseDispensateurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumeroDispensateurField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDeces {
            get {
                return this.DateDecesField;
            }
            set {
                if ((this.DateDecesField.Equals(value) != true)) {
                    this.DateDecesField = value;
                    this.RaisePropertyChanged("DateDeces");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DatePremiereSpecialite {
            get {
                return this.DatePremiereSpecialiteField;
            }
            set {
                if ((this.DatePremiereSpecialiteField.Equals(value) != true)) {
                    this.DatePremiereSpecialiteField = value;
                    this.RaisePropertyChanged("DatePremiereSpecialite");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroClasseDispensateur {
            get {
                return this.NumeroClasseDispensateurField;
            }
            set {
                if ((this.NumeroClasseDispensateurField.Equals(value) != true)) {
                    this.NumeroClasseDispensateurField = value;
                    this.RaisePropertyChanged("NumeroClasseDispensateur");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumeroDispensateur {
            get {
                return this.NumeroDispensateurField;
            }
            set {
                if ((this.NumeroDispensateurField.Equals(value) != true)) {
                    this.NumeroDispensateurField = value;
                    this.RaisePropertyChanged("NumeroDispensateur");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReductionRemunerationEntre", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Par" +
        "ametres")]
    [System.SerializableAttribute()]
    public partial class ReductionRemunerationEntre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumeroSequentielMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RpprUniquementField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NumeroSequentielMedecin {
            get {
                return this.NumeroSequentielMedecinField;
            }
            set {
                if ((this.NumeroSequentielMedecinField.Equals(value) != true)) {
                    this.NumeroSequentielMedecinField = value;
                    this.RaisePropertyChanged("NumeroSequentielMedecin");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RpprUniquement {
            get {
                return this.RpprUniquementField;
            }
            set {
                if ((object.ReferenceEquals(this.RpprUniquementField, value) != true)) {
                    this.RpprUniquementField = value;
                    this.RaisePropertyChanged("RpprUniquement");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParametreSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.EngagementPratique>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.EngagementPratique))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.Historique>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.Historique))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.Periode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Entite.InformationTerritoire))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Derogation.Entite.Derogation>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Entite.Derogation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ParamSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.MsgTrait>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.MsgTrait))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<System.DateTime>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<double>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Nullable<long>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementEntre))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Entite.AdmissibiliteFacturer>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Entite.AdmissibiliteFacturer))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Entite.EngagementPeriode>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Entite.EngagementPeriode))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<long>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemuneration>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemuneration))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactAvis>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactAvis))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactures))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactRSS>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactRSS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactTerritoire>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactTerritoire))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.CalculRPPR))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.EngagementProf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.EngagementProf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactDroitsAcquisDepassement>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactDroitsAcquisDepassement))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactDroitsAcquis))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.JoursFactDroitsAcquis>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.Message>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.RespectEngagementProfs>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.RespectEngagementProfs))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.SommaireProf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Pratique.Entite.SommaireProf))]
    public partial class ParametreSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<object> InfoMsgTraitField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<object> InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PLC2_CnsulProfiPremqProf_svc/1", ConfigurationName="svcCnsulProfiPremqProf.IServCnsulProfiPremqProf", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServCnsulProfiPremqProf {
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirLesEngageme" +
            "ntsPratiquesProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirLesEngageme" +
            "ntsPratiquesProfessionnelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirLesEngageme" +
            "ntsPratiquesProfessionnelExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti ObtenirLesEngagementsPratiquesProfessionnel(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirLesEngageme" +
            "ntsPratiquesProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirLesEngageme" +
            "ntsPratiquesProfessionnelResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti> ObtenirLesEngagementsPratiquesProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodePrat" +
            "iqueProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodePrat" +
            "iqueProfessionnelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodePrat" +
            "iqueProfessionnelExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti ObtenirPeriodePratiqueProfessionnel(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodePrat" +
            "iqueProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodePrat" +
            "iqueProfessionnelResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti> ObtenirPeriodePratiqueProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirDerogations" +
            "ProfessionnelSante", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirDerogations" +
            "ProfessionnelSanteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirDerogations" +
            "ProfessionnelSanteExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti ObtenirDerogationsProfessionnelSante(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirDerogations" +
            "ProfessionnelSante", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirDerogations" +
            "ProfessionnelSanteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti> ObtenirDerogationsProfessionnelSanteAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/VerifierAdmissibil" +
            "iteProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/VerifierAdmissibil" +
            "iteProfessionnelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/VerifierAdmissibil" +
            "iteProfessionnelExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti VerifierAdmissibiliteProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/VerifierAdmissibil" +
            "iteProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/VerifierAdmissibil" +
            "iteProfessionnelResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti> VerifierAdmissibiliteProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ModifierDerogation" +
            "", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ModifierDerogation" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ModifierDerogation" +
            "ExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti ModifierDerogation(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ModifierDerogation" +
            "", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ModifierDerogation" +
            "Response")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti> ModifierDerogationAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ValiderProfessionn" +
            "el", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ValiderProfessionn" +
            "elResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ValiderProfessionn" +
            "elExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti ValiderProfessionnel(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelEntre informationProfessionnel);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ValiderProfessionn" +
            "el", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ValiderProfessionn" +
            "elResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti> ValiderProfessionnelAsync(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelEntre informationProfessionnel);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/CalculerNombreJour" +
            "neeFacturation", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/CalculerNombreJour" +
            "neeFacturationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/CalculerNombreJour" +
            "neeFacturationExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti CalculerNombreJourneeFacturation(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/CalculerNombreJour" +
            "neeFacturation", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/CalculerNombreJour" +
            "neeFacturationResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti> CalculerNombreJourneeFacturationAsync(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirReductionRe" +
            "muneration", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirReductionRe" +
            "munerationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirReductionRe" +
            "munerationExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti ObtenirReductionRemuneration(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirReductionRe" +
            "muneration", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirReductionRe" +
            "munerationResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti> ObtenirReductionRemunerationAsync(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPourcentage" +
            "Maximum", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPourcentage" +
            "MaximumResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPourcentage" +
            "MaximumExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti ObtenirPourcentageMaximum();
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPourcentage" +
            "Maximum", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPourcentage" +
            "MaximumResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti> ObtenirPourcentageMaximumAsync();
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirInformation" +
            "Professionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirInformation" +
            "ProfessionnelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirInformation" +
            "ProfessionnelExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti ObtenirInformationProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirInformation" +
            "Professionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirInformation" +
            "ProfessionnelResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti> ObtenirInformationProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodeEnga" +
            "gementsAbsenceProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodeEnga" +
            "gementsAbsenceProfessionnelResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ExceptionRamq), Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodeEnga" +
            "gementsAbsenceProfessionnelExceptionRamqFault", Name="ExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementSorti ObtenirPeriodeEngagementsAbsenceProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementEntre intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodeEnga" +
            "gementsAbsenceProfessionnel", ReplyAction="http://PLC2_CnsulProfiPremqProf_svc/1/IServCnsulProfiPremqProf/ObtenirPeriodeEnga" +
            "gementsAbsenceProfessionnelResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementSorti> ObtenirPeriodeEngagementsAbsenceProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementEntre intrant);
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServCnsulProfiPremqProfChannel : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.IServCnsulProfiPremqProf, System.ServiceModel.IClientChannel {
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServCnsulProfiPremqProfClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.IServCnsulProfiPremqProf>, RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.IServCnsulProfiPremqProf {
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulProfiPremqProfClient() {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulProfiPremqProfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulProfiPremqProfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulProfiPremqProfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulProfiPremqProfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti ObtenirLesEngagementsPratiquesProfessionnel(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueEntre intrant) {
            return base.Channel.ObtenirLesEngagementsPratiquesProfessionnel(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueSorti> ObtenirLesEngagementsPratiquesProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.EngagementPratique.Parametre.ObtenirEngagementPratiqueEntre intrant) {
            return base.Channel.ObtenirLesEngagementsPratiquesProfessionnelAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti ObtenirPeriodePratiqueProfessionnel(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre intrant) {
            return base.Channel.ObtenirPeriodePratiqueProfessionnel(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti> ObtenirPeriodePratiqueProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre intrant) {
            return base.Channel.ObtenirPeriodePratiqueProfessionnelAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti ObtenirDerogationsProfessionnelSante(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant) {
            return base.Channel.ObtenirDerogationsProfessionnelSante(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti> ObtenirDerogationsProfessionnelSanteAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant) {
            return base.Channel.ObtenirDerogationsProfessionnelSanteAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti VerifierAdmissibiliteProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerEntre intrant) {
            return base.Channel.VerifierAdmissibiliteProfessionnel(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerSorti> VerifierAdmissibiliteProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.VerifierAdmissibiliteProfessionnelFacturerEntre intrant) {
            return base.Channel.VerifierAdmissibiliteProfessionnelAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti ModifierDerogation(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationEntre intrant) {
            return base.Channel.ModifierDerogation(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationSorti> ModifierDerogationAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ModifierDerogationEntre intrant) {
            return base.Channel.ModifierDerogationAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti ValiderProfessionnel(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelEntre informationProfessionnel) {
            return base.Channel.ValiderProfessionnel(informationProfessionnel);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelSorti> ValiderProfessionnelAsync(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ValiderProfessionnelEntre informationProfessionnel) {
            return base.Channel.ValiderProfessionnelAsync(informationProfessionnel);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti CalculerNombreJourneeFacturation(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre intrant) {
            return base.Channel.CalculerNombreJourneeFacturation(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti> CalculerNombreJourneeFacturationAsync(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre intrant) {
            return base.Channel.CalculerNombreJourneeFacturationAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti ObtenirReductionRemuneration(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationEntre intrant) {
            return base.Channel.ObtenirReductionRemuneration(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationSorti> ObtenirReductionRemunerationAsync(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ReductionRemunerationEntre intrant) {
            return base.Channel.ObtenirReductionRemunerationAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti ObtenirPourcentageMaximum() {
            return base.Channel.ObtenirPourcentageMaximum();
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulProfiPremqProf.ObtenirPourcentageMaximumSorti> ObtenirPourcentageMaximumAsync() {
            return base.Channel.ObtenirPourcentageMaximumAsync();
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti ObtenirInformationProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuEntre intrant) {
            return base.Channel.ObtenirInformationProfessionnel(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuSorti> ObtenirInformationProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirDispensateurIndividuEntre intrant) {
            return base.Channel.ObtenirInformationProfessionnelAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementSorti ObtenirPeriodeEngagementsAbsenceProfessionnel(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementEntre intrant) {
            return base.Channel.ObtenirPeriodeEngagementsAbsenceProfessionnel(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementSorti> ObtenirPeriodeEngagementsAbsenceProfessionnelAsync(RAMQ.PRE.PRE_Entites_cpo.Professionnel.Parametre.ObtenirVuePeriodeEngagementEntre intrant) {
            return base.Channel.ObtenirPeriodeEngagementsAbsenceProfessionnelAsync(intrant);
        }
    }
}
