//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteSorti))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.MsgTrait> InfoMsgTraitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.MsgTrait> InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnConfirmationSuspPDFSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationSuspension.Param")]
    [System.SerializableAttribute()]
    public partial class ObtnConfirmationSuspPDFSorti : RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ParamSorti {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] GabaritPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GabaritPDF {
            get {
                return this.GabaritPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.GabaritPDFField, value) != true)) {
                    this.GabaritPDFField = value;
                    this.RaisePropertyChanged("GabaritPDF");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnConfirmationDerogPDFSorti", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationDerogation.Param")]
    [System.SerializableAttribute()]
    public partial class ObtnConfirmationDerogPDFSorti : RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ParamSorti {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] GabaritPDFField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] GabaritPDF {
            get {
                return this.GabaritPDFField;
            }
            set {
                if ((object.ReferenceEquals(this.GabaritPDFField, value) != true)) {
                    this.GabaritPDFField = value;
                    this.RaisePropertyChanged("GabaritPDF");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class ExceptionRamqIntrn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string PileAppelField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.InnerExceptionRamq> InnerExceptionField;
        
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PileAppel {
            get {
                return this.PileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.PileAppelField, value) != true)) {
                    this.PileAppelField = value;
                    this.RaisePropertyChanged("PileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.InnerExceptionRamq> InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class InnerExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InnerMessageField;
        
        private string InnerPileAppelField;
        
        private string InnerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerMessage {
            get {
                return this.InnerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerMessageField, value) != true)) {
                    this.InnerMessageField = value;
                    this.RaisePropertyChanged("InnerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerPileAppel {
            get {
                return this.InnerPileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerPileAppelField, value) != true)) {
                    this.InnerPileAppelField = value;
                    this.RaisePropertyChanged("InnerPileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerType {
            get {
                return this.InnerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerTypeField, value) != true)) {
                    this.InnerTypeField = value;
                    this.RaisePropertyChanged("InnerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnConfirmationDerogPDFEntre", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationDerogation.Param")]
    [System.SerializableAttribute()]
    public partial class ObtnConfirmationDerogPDFEntre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageInformatifComplementaireField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.TypeActionDerogtion TypeActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeDerogationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDebutField, value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationMedecin {
            get {
                return this.IdentificationMedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationMedecinField, value) != true)) {
                    this.IdentificationMedecinField = value;
                    this.RaisePropertyChanged("IdentificationMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageConfirmation {
            get {
                return this.MessageConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageConfirmationField, value) != true)) {
                    this.MessageConfirmationField = value;
                    this.RaisePropertyChanged("MessageConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageInformatifComplementaire {
            get {
                return this.MessageInformatifComplementaireField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageInformatifComplementaireField, value) != true)) {
                    this.MessageInformatifComplementaireField = value;
                    this.RaisePropertyChanged("MessageInformatifComplementaire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.TypeActionDerogtion TypeAction {
            get {
                return this.TypeActionField;
            }
            set {
                if ((this.TypeActionField.Equals(value) != true)) {
                    this.TypeActionField = value;
                    this.RaisePropertyChanged("TypeAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeDerogation {
            get {
                return this.TypeDerogationField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeDerogationField, value) != true)) {
                    this.TypeDerogationField = value;
                    this.RaisePropertyChanged("TypeDerogation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeActionDerogtion", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationDerogation")]
    public enum TypeActionDerogtion : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Autre = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transmettre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annule = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtnConfirmationSuspPDFEntre", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationSuspension.Param")]
    [System.SerializableAttribute()]
    public partial class ObtnConfirmationSuspPDFEntre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvisConformiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDebutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDebutPerModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFinPerModifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificationMedecinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageConfirmationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.TypeActionSuspension TypeActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeSuspensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvisConformite {
            get {
                return this.AvisConformiteField;
            }
            set {
                if ((object.ReferenceEquals(this.AvisConformiteField, value) != true)) {
                    this.AvisConformiteField = value;
                    this.RaisePropertyChanged("AvisConformite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDebut {
            get {
                return this.DateDebutField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDebutField, value) != true)) {
                    this.DateDebutField = value;
                    this.RaisePropertyChanged("DateDebut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateDebutPerModif {
            get {
                return this.DateDebutPerModifField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDebutPerModifField, value) != true)) {
                    this.DateDebutPerModifField = value;
                    this.RaisePropertyChanged("DateDebutPerModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFin {
            get {
                return this.DateFinField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFinField, value) != true)) {
                    this.DateFinField = value;
                    this.RaisePropertyChanged("DateFin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFinPerModif {
            get {
                return this.DateFinPerModifField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFinPerModifField, value) != true)) {
                    this.DateFinPerModifField = value;
                    this.RaisePropertyChanged("DateFinPerModif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificationMedecin {
            get {
                return this.IdentificationMedecinField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificationMedecinField, value) != true)) {
                    this.IdentificationMedecinField = value;
                    this.RaisePropertyChanged("IdentificationMedecin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageConfirmation {
            get {
                return this.MessageConfirmationField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageConfirmationField, value) != true)) {
                    this.MessageConfirmationField = value;
                    this.RaisePropertyChanged("MessageConfirmation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.TypeActionSuspension TypeAction {
            get {
                return this.TypeActionField;
            }
            set {
                if ((this.TypeActionField.Equals(value) != true)) {
                    this.TypeActionField = value;
                    this.RaisePropertyChanged("TypeAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeSuspension {
            get {
                return this.TypeSuspensionField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeSuspensionField, value) != true)) {
                    this.TypeSuspensionField = value;
                    this.RaisePropertyChanged("TypeSuspension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeActionSuspension", Namespace="http://schemas.datacontract.org/2004/07/RAMQ.PRE.PLA2_SaisDecisAvisConf_cpo.Confi" +
        "rmationSuspension")]
    public enum TypeActionSuspension : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Autre = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transmettre = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Annule = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modification = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PLA2_SaisDecisAvisConf_svc/1", ConfigurationName="svcSaisDecisAvisConf.IServSaisDecisAvisConf", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServSaisDecisAvisConf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterDerogationAvisC" +
            "onformite", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterDerogationAvisC" +
            "onformiteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterDerogationAvisC" +
            "onformiteExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteSorti TraiterDerogationAvisConformite(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterDerogationAvisC" +
            "onformite", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterDerogationAvisC" +
            "onformiteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteSorti> TraiterDerogationAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterSuspensionAvisC" +
            "onformite", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterSuspensionAvisC" +
            "onformiteResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterSuspensionAvisC" +
            "onformiteExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteSorti TraiterSuspensionAvisConformite(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterSuspensionAvisC" +
            "onformite", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterSuspensionAvisC" +
            "onformiteResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteSorti> TraiterSuspensionAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterAnnulationDerog" +
            "ation", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterAnnulationDerog" +
            "ationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterAnnulationDerog" +
            "ationExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationSorti TraiterAnnulationDerogation(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterAnnulationDerog" +
            "ation", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/TraiterAnnulationDerog" +
            "ationResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationSorti> TraiterAnnulationDerogationAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirDerogations", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirDerogationsResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirDerogationsExce" +
            "ptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti ObtenirDerogations(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirDerogations", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirDerogationsResp" +
            "onse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti> ObtenirDerogationsAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionDerog", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionDerogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionDerogExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFSorti ObtenirGabaritConfirmationDerog(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFEntre parametreEntre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionDerog", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionDerogResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFSorti> ObtenirGabaritConfirmationDerogAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFEntre parametreEntre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionSusp", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionSuspResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ExceptionRamqIntrn), Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionSuspExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFSorti ObtenirGabaritConfirmationSusp(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFEntre parametreEntre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionSusp", ReplyAction="http://PLA2_SaisDecisAvisConf_svc/1/IServSaisDecisAvisConf/ObtenirGabaritConfirma" +
            "tionSuspResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFSorti> ObtenirGabaritConfirmationSuspAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFEntre parametreEntre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServSaisDecisAvisConfChannel : RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.IServSaisDecisAvisConf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServSaisDecisAvisConfClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.IServSaisDecisAvisConf>, RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.IServSaisDecisAvisConf {
        
        public ServSaisDecisAvisConfClient() {
        }
        
        public ServSaisDecisAvisConfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServSaisDecisAvisConfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServSaisDecisAvisConfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServSaisDecisAvisConfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteSorti TraiterDerogationAvisConformite(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteEntre intrant) {
            return base.Channel.TraiterDerogationAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteSorti> TraiterDerogationAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterDerogationAvisConformiteEntre intrant) {
            return base.Channel.TraiterDerogationAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteSorti TraiterSuspensionAvisConformite(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteEntre intrant) {
            return base.Channel.TraiterSuspensionAvisConformite(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteSorti> TraiterSuspensionAvisConformiteAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterSuspensionAvisConformiteEntre intrant) {
            return base.Channel.TraiterSuspensionAvisConformiteAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationSorti TraiterAnnulationDerogation(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationEntre intrant) {
            return base.Channel.TraiterAnnulationDerogation(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationSorti> TraiterAnnulationDerogationAsync(RAMQ.PRE.PRE_Entites_cpo.DecisionAvisConformite.Parametre.TraiterAnnulationDerogationEntre intrant) {
            return base.Channel.TraiterAnnulationDerogationAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti ObtenirDerogations(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant) {
            return base.Channel.ObtenirDerogations(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteSorti> ObtenirDerogationsAsync(RAMQ.PRE.PRE_Entites_cpo.Derogation.Parametre.ObtenirDerogationsProfessionnelSanteEntre intrant) {
            return base.Channel.ObtenirDerogationsAsync(intrant);
        }
        
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFSorti ObtenirGabaritConfirmationDerog(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmationDerog(parametreEntre);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFSorti> ObtenirGabaritConfirmationDerogAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationDerogPDFEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmationDerogAsync(parametreEntre);
        }
        
        public RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFSorti ObtenirGabaritConfirmationSusp(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmationSusp(parametreEntre);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFSorti> ObtenirGabaritConfirmationSuspAsync(RAMQ.PRE.PL_PremMdl_cpo.svcSaisDecisAvisConf.ObtnConfirmationSuspPDFEntre parametreEntre) {
            return base.Channel.ObtenirGabaritConfirmationSuspAsync(parametreEntre);
        }
    }
}
