//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp {
    using System.Runtime.Serialization;
    using System;
    
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportExerNonAutoRPPR>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.MsgTrait[] InfoMsgTraitField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.MsgTrait[] InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class ExceptionRamqIntrn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string PileAppelField;
        
        private RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.InnerExceptionRamq[] InnerExceptionField;
        
        private string TypeField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PileAppel {
            get {
                return this.PileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.PileAppelField, value) != true)) {
                    this.PileAppelField = value;
                    this.RaisePropertyChanged("PileAppel");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.InnerExceptionRamq[] InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class InnerExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InnerMessageField;
        
        private string InnerPileAppelField;
        
        private string InnerTypeField;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerMessage {
            get {
                return this.InnerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerMessageField, value) != true)) {
                    this.InnerMessageField = value;
                    this.RaisePropertyChanged("InnerMessage");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerPileAppel {
            get {
                return this.InnerPileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerPileAppelField, value) != true)) {
                    this.InnerPileAppelField = value;
                    this.RaisePropertyChanged("InnerPileAppel");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerType {
            get {
                return this.InnerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerTypeField, value) != true)) {
                    this.InnerTypeField = value;
                    this.RaisePropertyChanged("InnerType");
                }
            }
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif", ConfigurationName="svcCnsulRapp.IServCnsulRappPremq", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServCnsulRappPremq {
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf> ObtenirRapportNonRespAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>> ObtenirRapportNonRespAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportDerogPratiExcluFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportDerogPratiExcluFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu> ObtenirRapportDerogPratiExcluWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>> ObtenirRapportDerogPratiExcluWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportExerNonAutoRPPRFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportExerNonAutoRPPRFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportExerNonAutoRPPR> ObtenirRapportExerNonAutoRPPRWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "ExerNonAutoRPPRWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportExerNonAutoRPPR>> ObtenirRapportExerNonAutoRPPRWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportRepartInterRegionPratiFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportRepartInterRegionPratiFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati> ObtenirRapportRepartInterRegionPratiWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant);
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>> ObtenirRapportRepartInterRegionPratiWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant);
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServCnsulRappPremqChannel : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq, System.ServiceModel.IClientChannel {
    }
    
    /// <exclude>
    /// <summary>
    /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
    /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
    /// </summary>
    /// </exclude>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServCnsulRappPremqClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq>, RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq {
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulRappPremqClient() {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulRappPremqClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulRappPremqClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulRappPremqClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public ServCnsulRappPremqClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespAvisConfFichier(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespAvisConfFichierAsync(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf> ObtenirRapportNonRespAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant) {
            return base.Channel.ObtenirRapportNonRespAvisConfWeb(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>> ObtenirRapportNonRespAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant) {
            return base.Channel.ObtenirRapportNonRespAvisConfWebAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportDerogPratiExcluFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportDerogPratiExcluFichier(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportDerogPratiExcluFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportDerogPratiExcluFichierAsync(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu> ObtenirRapportDerogPratiExcluWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant) {
            return base.Channel.ObtenirRapportDerogPratiExcluWeb(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>> ObtenirRapportDerogPratiExcluWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant) {
            return base.Channel.ObtenirRapportDerogPratiExcluWebAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportExerNonAutoRPPRFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportExerNonAutoRPPRFichier(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportExerNonAutoRPPRFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportExerNonAutoRPPRFichierAsync(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportExerNonAutoRPPR> ObtenirRapportExerNonAutoRPPRWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant) {
            return base.Channel.ObtenirRapportExerNonAutoRPPRWeb(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportExerNonAutoRPPR>> ObtenirRapportExerNonAutoRPPRWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappExerNonAutoRPPR intrant) {
            return base.Channel.ObtenirRapportExerNonAutoRPPRWebAsync(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportRepartInterRegionPratiFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiFichier(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportRepartInterRegionPratiFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiFichierAsync(intrant, enumTypeFichier);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati> ObtenirRapportRepartInterRegionPratiWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiWeb(intrant);
        }
        
        /// <exclude>
        /// <summary>
        /// Un résumé a été ajouter pour prévenir les avertissements nous informant qu'il n'y a pas de documentation XML pour les membres visibles.
        /// La balise "exclude" sert à empêcher SandCastle de générer une documentation pour les références de services.
        /// </summary>
        /// </exclude>
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>> ObtenirRapportRepartInterRegionPratiWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiWebAsync(intrant);
        }
    }
}
