//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAbsncAvisConf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfActifsParTerritoire>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfTermines>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespPourcMaxReconRPPR>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNouvMedSansAvisConf>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti))]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.MsgTrait[] InfoMsgTraitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.MsgTrait[] InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public partial class ExceptionRamqIntrn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string PileAppelField;
        
        private RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.InnerExceptionRamq[] InnerExceptionField;
        
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PileAppel {
            get {
                return this.PileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.PileAppelField, value) != true)) {
                    this.PileAppelField = value;
                    this.RaisePropertyChanged("PileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.InnerExceptionRamq[] InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public partial class InnerExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InnerMessageField;
        
        private string InnerPileAppelField;
        
        private string InnerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerMessage {
            get {
                return this.InnerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerMessageField, value) != true)) {
                    this.InnerMessageField = value;
                    this.RaisePropertyChanged("InnerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerPileAppel {
            get {
                return this.InnerPileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerPileAppelField, value) != true)) {
                    this.InnerPileAppelField = value;
                    this.RaisePropertyChanged("InnerPileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerType {
            get {
                return this.InnerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerTypeField, value) != true)) {
                    this.InnerTypeField = value;
                    this.RaisePropertyChanged("InnerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif", ConfigurationName="svcCnsulRapp.IServCnsulRappPremq", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public interface IServCnsulRappPremq {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAbsncAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAbsncAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAbsncAvisConf> ObtenirRapportAbsncAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AbsncAvisConfWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAbsncAvisConf>> ObtenirRapportAbsncAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAvisConfActifsParTerritoireFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAvisConfActifsParTerritoireFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfActifsParTerritoire> ObtenirRapportAvisConfActifsParTerritoireWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfActifsParTerritoireWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfActifsParTerritoire>> ObtenirRapportAvisConfActifsParTerritoireWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAvisConfTerminesFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAvisConfTerminesFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfTermines> ObtenirRapportAvisConfTerminesWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "AvisConfTerminesWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfTermines>> ObtenirRapportAvisConfTerminesWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportDerogPratiExcluFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportDerogPratiExcluFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu> ObtenirRapportDerogPratiExcluWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "DerogPratiExcluWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>> ObtenirRapportDerogPratiExcluWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf> ObtenirRapportNonRespAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespAvisConfWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>> ObtenirRapportNonRespAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespPourcMaxReconRPPRFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespPourcMaxReconRPPRFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespPourcMaxReconRPPR> ObtenirRapportNonRespPourcMaxReconRPPRWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NonRespPourcMaxReconRPPRWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespPourcMaxReconRPPR>> ObtenirRapportNonRespPourcMaxReconRPPRWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNouvMedSansAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNouvMedSansAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNouvMedSansAvisConf> ObtenirRapportNouvMedSansAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "NouvMedSansAvisConfWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNouvMedSansAvisConf>> ObtenirRapportNouvMedSansAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportRepartInterRegionPratiFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichier", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiFichierResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportRepartInterRegionPratiFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.ExceptionRamqIntrn), Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati> ObtenirRapportRepartInterRegionPratiWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWeb", ReplyAction="http://www.ramq.gouv.qc.ca/PRE/NomSignificatif/IServCnsulRappPremq/ObtenirRapport" +
            "RepartInterRegionPratiWebResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>> ObtenirRapportRepartInterRegionPratiWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public interface IServCnsulRappPremqChannel : RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.‌​Usage", "CS1591")]
    public partial class ServCnsulRappPremqClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq>, RAMQ.PRE.PL_PremMdl_cpo.svcCnsulRapp.IServCnsulRappPremq {
        
        public ServCnsulRappPremqClient() {
        }
        
        public ServCnsulRappPremqClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServCnsulRappPremqClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServCnsulRappPremqClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServCnsulRappPremqClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAbsncAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAbsncAvisConfFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAbsncAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAbsncAvisConfFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAbsncAvisConf> ObtenirRapportAbsncAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant) {
            return base.Channel.ObtenirRapportAbsncAvisConfWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAbsncAvisConf>> ObtenirRapportAbsncAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAbsncAvisConf intrant) {
            return base.Channel.ObtenirRapportAbsncAvisConfWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAvisConfActifsParTerritoireFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAvisConfActifsParTerritoireFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAvisConfActifsParTerritoireFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAvisConfActifsParTerritoireFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfActifsParTerritoire> ObtenirRapportAvisConfActifsParTerritoireWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant) {
            return base.Channel.ObtenirRapportAvisConfActifsParTerritoireWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfActifsParTerritoire>> ObtenirRapportAvisConfActifsParTerritoireWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfActifsParTerritoire intrant) {
            return base.Channel.ObtenirRapportAvisConfActifsParTerritoireWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportAvisConfTerminesFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAvisConfTerminesFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportAvisConfTerminesFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportAvisConfTerminesFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfTermines> ObtenirRapportAvisConfTerminesWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant) {
            return base.Channel.ObtenirRapportAvisConfTerminesWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportAvisConfTermines>> ObtenirRapportAvisConfTerminesWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappAvisConfTermines intrant) {
            return base.Channel.ObtenirRapportAvisConfTerminesWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportDerogPratiExcluFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportDerogPratiExcluFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportDerogPratiExcluFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportDerogPratiExcluFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu> ObtenirRapportDerogPratiExcluWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant) {
            return base.Channel.ObtenirRapportDerogPratiExcluWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportDerogPratiExclu>> ObtenirRapportDerogPratiExcluWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappDerogPratiExclu intrant) {
            return base.Channel.ObtenirRapportDerogPratiExcluWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespAvisConfFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespAvisConfFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf> ObtenirRapportNonRespAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant) {
            return base.Channel.ObtenirRapportNonRespAvisConfWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespAvisConf>> ObtenirRapportNonRespAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespAvisConf intrant) {
            return base.Channel.ObtenirRapportNonRespAvisConfWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNonRespPourcMaxReconRPPRFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespPourcMaxReconRPPRFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNonRespPourcMaxReconRPPRFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNonRespPourcMaxReconRPPRFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespPourcMaxReconRPPR> ObtenirRapportNonRespPourcMaxReconRPPRWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant) {
            return base.Channel.ObtenirRapportNonRespPourcMaxReconRPPRWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNonRespPourcMaxReconRPPR>> ObtenirRapportNonRespPourcMaxReconRPPRWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNonRespPourcMaxReconRPPR intrant) {
            return base.Channel.ObtenirRapportNonRespPourcMaxReconRPPRWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportNouvMedSansAvisConfFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNouvMedSansAvisConfFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportNouvMedSansAvisConfFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportNouvMedSansAvisConfFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNouvMedSansAvisConf> ObtenirRapportNouvMedSansAvisConfWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant) {
            return base.Channel.ObtenirRapportNouvMedSansAvisConfWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportNouvMedSansAvisConf>> ObtenirRapportNouvMedSansAvisConfWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappNouvMedSansAvisConf intrant) {
            return base.Channel.ObtenirRapportNouvMedSansAvisConfWebAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti ObtenirRapportRepartInterRegionPratiFichier(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiFichier(intrant, enumTypeFichier);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportFichierSorti> ObtenirRapportRepartInterRegionPratiFichierAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant, RAMQ.PRE.PRE_Entites_cpo.Enumerations.TypeFichierSortieRapport enumTypeFichier) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiFichierAsync(intrant, enumTypeFichier);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati> ObtenirRapportRepartInterRegionPratiWeb(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiWeb(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnRapportWebSorti<RAMQ.PRE.PRE_Entites_cpo.Rapport.Entite.LigneRapportRepartInterRegionPrati>> ObtenirRapportRepartInterRegionPratiWebAsync(RAMQ.PRE.PRE_Entites_cpo.Rapport.Parametre.ParamObtnrRappRepartInterRegionPrati intrant) {
            return base.Channel.ObtenirRapportRepartInterRegionPratiWebAsync(intrant);
        }
    }
}
