//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParamSorti", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCSortie))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisSorti))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssSorti))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.MsgTrait> InfoMsgTraitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.MsgTrait> InfoMsgTrait {
            get {
                return this.InfoMsgTraitField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true)) {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MsgTrait", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodAppliField;
        
        private string IdMsgField;
        
        private string CodSeverField;
        
        private string TxtMsgFranField;
        
        private string TxtMsgAnglField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodAppli {
            get {
                return this.CodAppliField;
            }
            set {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true)) {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdMsg {
            get {
                return this.IdMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true)) {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string CodSever {
            get {
                return this.CodSeverField;
            }
            set {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true)) {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string TxtMsgFran {
            get {
                return this.TxtMsgFranField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true)) {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string TxtMsgAngl {
            get {
                return this.TxtMsgAnglField;
            }
            set {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true)) {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class ExceptionRamqIntrn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private string PileAppelField;
        
        private System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.InnerExceptionRamq> InnerExceptionField;
        
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PileAppel {
            get {
                return this.PileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.PileAppelField, value) != true)) {
                    this.PileAppelField = value;
                    this.RaisePropertyChanged("PileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Collections.Generic.List<RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.InnerExceptionRamq> InnerException {
            get {
                return this.InnerExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerExceptionField, value) != true)) {
                    this.InnerExceptionField = value;
                    this.RaisePropertyChanged("InnerException");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InnerExceptionRamq", Namespace="http://COD1_V4OutilBase_cpo/2")]
    [System.SerializableAttribute()]
    public partial class InnerExceptionRamq : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string InnerMessageField;
        
        private string InnerPileAppelField;
        
        private string InnerTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerMessage {
            get {
                return this.InnerMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerMessageField, value) != true)) {
                    this.InnerMessageField = value;
                    this.RaisePropertyChanged("InnerMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerPileAppel {
            get {
                return this.InnerPileAppelField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerPileAppelField, value) != true)) {
                    this.InnerPileAppelField = value;
                    this.RaisePropertyChanged("InnerPileAppel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string InnerType {
            get {
                return this.InnerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerTypeField, value) != true)) {
                    this.InnerTypeField = value;
                    this.RaisePropertyChanged("InnerType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://PLA1_SaisAvisConf_svc/1", ConfigurationName="svcLieuxGeographiques.IServLieuxGeographiques", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IServLieuxGeographiques {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirRegroupementsLieuxG" +
            "eographiquesRSS", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirRegroupementsLieuxG" +
            "eographiquesRSSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirRegroupementsLieuxG" +
            "eographiquesRSSExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssSorti ObtenirRegroupementsLieuxGeographiquesRSS(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirRegroupementsLieuxG" +
            "eographiquesRSS", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirRegroupementsLieuxG" +
            "eographiquesRSSResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssSorti> ObtenirRegroupementsLieuxGeographiquesRSSAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireCL" +
            "SC", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireCL" +
            "SCResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireCL" +
            "SCExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCSortie ObtenirLesNomsTerritoireCLSC(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireCL" +
            "SC", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireCL" +
            "SCResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCSortie> ObtenirLesNomsTerritoireCLSCAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireRL" +
            "S", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireRL" +
            "SResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireRL" +
            "SExceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSSorti ObtenirLesNomsTerritoireRLS(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireRL" +
            "S", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirLesNomsTerritoireRL" +
            "SResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSSorti> ObtenirLesNomsTerritoireRLSAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirNomTerritoire", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirNomTerritoireRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirNomTerritoireExcept" +
            "ionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireSorti ObtenirNomTerritoire(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirNomTerritoire", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirNomTerritoireRespon" +
            "se")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireSorti> ObtenirNomTerritoireAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirTerritoiresPermis", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirTerritoiresPermisRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.ExceptionRamqIntrn), Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirTerritoiresPermisEx" +
            "ceptionRamqIntrnFault", Name="ExceptionRamqIntrn", Namespace="http://COD1_V4OutilBase_cpo/2")]
        RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisSorti ObtenirTerritoiresPermis(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisEntre intrant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirTerritoiresPermis", ReplyAction="http://PLA1_SaisAvisConf_svc/1/IServLieuxGeographiques/ObtenirTerritoiresPermisRe" +
            "sponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisSorti> ObtenirTerritoiresPermisAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisEntre intrant);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServLieuxGeographiquesChannel : RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.IServLieuxGeographiques, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServLieuxGeographiquesClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.IServLieuxGeographiques>, RAMQ.PRE.PL_PremMdl_cpo.svcLieuxGeographiques.IServLieuxGeographiques {
        
        public ServLieuxGeographiquesClient() {
        }
        
        public ServLieuxGeographiquesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServLieuxGeographiquesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLieuxGeographiquesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServLieuxGeographiquesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssSorti ObtenirRegroupementsLieuxGeographiquesRSS(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssEntre intrant) {
            return base.Channel.ObtenirRegroupementsLieuxGeographiquesRSS(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssSorti> ObtenirRegroupementsLieuxGeographiquesRSSAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirRegroupementsLgeoRssEntre intrant) {
            return base.Channel.ObtenirRegroupementsLieuxGeographiquesRSSAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCSortie ObtenirLesNomsTerritoireCLSC(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCEntre intrant) {
            return base.Channel.ObtenirLesNomsTerritoireCLSC(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCSortie> ObtenirLesNomsTerritoireCLSCAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireCLSCEntre intrant) {
            return base.Channel.ObtenirLesNomsTerritoireCLSCAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSSorti ObtenirLesNomsTerritoireRLS(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSEntre intrant) {
            return base.Channel.ObtenirLesNomsTerritoireRLS(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSSorti> ObtenirLesNomsTerritoireRLSAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirInformationTerritoireRLSEntre intrant) {
            return base.Channel.ObtenirLesNomsTerritoireRLSAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireSorti ObtenirNomTerritoire(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireEntre intrant) {
            return base.Channel.ObtenirNomTerritoire(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireSorti> ObtenirNomTerritoireAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirNomTerritoireEntre intrant) {
            return base.Channel.ObtenirNomTerritoireAsync(intrant);
        }
        
        public RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisSorti ObtenirTerritoiresPermis(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisEntre intrant) {
            return base.Channel.ObtenirTerritoiresPermis(intrant);
        }
        
        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisSorti> ObtenirTerritoiresPermisAsync(RAMQ.PRE.PRE_Entites_cpo.LieuGeographique.Parametre.ObtenirTerritoiresPermisEntre intrant) {
            return base.Channel.ObtenirTerritoiresPermisAsync(intrant);
        }
    }
}
