
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PRE_SysExt_cpo.FIP.EPZ3.Parametre.ObtenirPeriodePratiqueProfessionnelSorti,RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelSorti@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PRE_Entites_cpo.PeriodePratique.Parametre.ObtenirPeriodePratiqueProfessionnelEntre,RAMQ.PRE.PRE_SysExt_cpo.FIP.EPZ3.Parametre.ObtenirPeriodePratiqueProfessionnelEntre@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Parametres.CalculerNombreJourneeFacturationEntre,RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsEntre,RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Parametres.CalculerNombreJourneeFacturationEntre@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Parametres.CalculerNombreJourneeFacturationSorti,RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Maintenance", "RAMQ0101:Règle RAMQ 7.8 : L'utilisation du mot clé 'ref' ou 'out' n'est pas recommandé.", Justification = "<En attente>", Scope = "member", Target = "~M:RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Utilitaire.Mappeur.Mapper(RAMQ.PRE.PRE_Entites_cpo.Pratique.Parametre.CalculerNbrJrFactProfsSorti,RAMQ.PRE.PLC2_CnsulProfiPremqProf_cpo.Parametres.CalculerNombreJourneeFacturationSorti@)")]

