//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnNomLoc", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnNomLoc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.DateTime DateEntreField;

        private string ListeLocCodField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime DateEntre
        {
            get
            {
                return this.DateEntreField;
            }
            set
            {
                if ((this.DateEntreField.Equals(value) != true))
                {
                    this.DateEntreField = value;
                    this.RaisePropertyChanged("DateEntre");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ListeLocCod
        {
            get
            {
                return this.ListeLocCodField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListeLocCodField, value) != true))
                {
                    this.ListeLocCodField = value;
                    this.RaisePropertyChanged("ListeLocCod");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ParamSorti", Namespace = "http://COD1_V4OutilBase_cpo/1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoPays))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCP))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCodLocal))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnCodRSS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoLocalPart))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTau))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriRLS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriCLSC))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnNomLoc))]
    public partial class ParamSorti : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private System.Collections.Generic.List<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.MsgTrait> InfoMsgTraitField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.MsgTrait> InfoMsgTrait
        {
            get
            {
                return this.InfoMsgTraitField;
            }
            set
            {
                if ((object.ReferenceEquals(this.InfoMsgTraitField, value) != true))
                {
                    this.InfoMsgTraitField = value;
                    this.RaisePropertyChanged("InfoMsgTrait");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnInfoPays", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnInfoPays : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<int> CodPaysField;

        private System.Collections.Generic.List<string> NomPaysFranField;

        private System.Collections.Generic.List<string> NomAbrPaysFranField;

        private System.Collections.Generic.List<string> NomPaysAnglField;

        private System.Collections.Generic.List<string> NomAbrPaysAnglField;

        private System.Collections.Generic.List<string> CodPaysCar2Field;

        private System.Collections.Generic.List<string> CodPaysCar3Field;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.Collections.Generic.List<int> CodPays
        {
            get
            {
                return this.CodPaysField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodPaysField, value) != true))
                {
                    this.CodPaysField = value;
                    this.RaisePropertyChanged("CodPays");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Collections.Generic.List<string> NomPaysFran
        {
            get
            {
                return this.NomPaysFranField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPaysFranField, value) != true))
                {
                    this.NomPaysFranField = value;
                    this.RaisePropertyChanged("NomPaysFran");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<string> NomAbrPaysFran
        {
            get
            {
                return this.NomAbrPaysFranField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomAbrPaysFranField, value) != true))
                {
                    this.NomAbrPaysFranField = value;
                    this.RaisePropertyChanged("NomAbrPaysFran");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public System.Collections.Generic.List<string> NomPaysAngl
        {
            get
            {
                return this.NomPaysAnglField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPaysAnglField, value) != true))
                {
                    this.NomPaysAnglField = value;
                    this.RaisePropertyChanged("NomPaysAngl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public System.Collections.Generic.List<string> NomAbrPaysAngl
        {
            get
            {
                return this.NomAbrPaysAnglField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomAbrPaysAnglField, value) != true))
                {
                    this.NomAbrPaysAnglField = value;
                    this.RaisePropertyChanged("NomAbrPaysAngl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public System.Collections.Generic.List<string> CodPaysCar2
        {
            get
            {
                return this.CodPaysCar2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodPaysCar2Field, value) != true))
                {
                    this.CodPaysCar2Field = value;
                    this.RaisePropertyChanged("CodPaysCar2");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public System.Collections.Generic.List<string> CodPaysCar3
        {
            get
            {
                return this.CodPaysCar3Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodPaysCar3Field, value) != true))
                {
                    this.CodPaysCar3Field = value;
                    this.RaisePropertyChanged("CodPaysCar3");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnTerriCLSCCP", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnTerriCLSCCP : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CPField;

        private System.Collections.Generic.List<string> CodTerriCLSCField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.Collections.Generic.List<string> CP
        {
            get
            {
                return this.CPField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CPField, value) != true))
                {
                    this.CPField = value;
                    this.RaisePropertyChanged("CP");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Collections.Generic.List<string> CodTerriCLSC
        {
            get
            {
                return this.CodTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriCLSCField, value) != true))
                {
                    this.CodTerriCLSCField = value;
                    this.RaisePropertyChanged("CodTerriCLSC");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnTerriCLSCCodLocal", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnTerriCLSCCodLocal : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CodLocalField;

        private System.Collections.Generic.List<string> NomMunicField;

        private System.Collections.Generic.List<string> CodTerriCLSCField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.Collections.Generic.List<string> CodLocal
        {
            get
            {
                return this.CodLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodLocalField, value) != true))
                {
                    this.CodLocalField = value;
                    this.RaisePropertyChanged("CodLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Collections.Generic.List<string> NomMunic
        {
            get
            {
                return this.NomMunicField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomMunicField, value) != true))
                {
                    this.NomMunicField = value;
                    this.RaisePropertyChanged("NomMunic");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<string> CodTerriCLSC
        {
            get
            {
                return this.CodTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriCLSCField, value) != true))
                {
                    this.CodTerriCLSCField = value;
                    this.RaisePropertyChanged("CodTerriCLSC");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnCodRSS", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnCodRSS : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CodLocalField;

        private System.Collections.Generic.List<string> CodRSSField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.Collections.Generic.List<string> CodLocal
        {
            get
            {
                return this.CodLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodLocalField, value) != true))
                {
                    this.CodLocalField = value;
                    this.RaisePropertyChanged("CodLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Collections.Generic.List<string> CodRSS
        {
            get
            {
                return this.CodRSSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRSSField, value) != true))
                {
                    this.CodRSSField = value;
                    this.RaisePropertyChanged("CodRSS");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnInfoLocalPart", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnInfoLocalPart : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CodLocalField;

        private System.Collections.Generic.List<string> NomLocalField;

        private System.Collections.Generic.List<System.Nullable<System.DateTime>> DdLocalField;

        private System.Collections.Generic.List<System.Nullable<System.DateTime>> DfLocalField;

        private int NbrOccField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.Collections.Generic.List<string> CodLocal
        {
            get
            {
                return this.CodLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodLocalField, value) != true))
                {
                    this.CodLocalField = value;
                    this.RaisePropertyChanged("CodLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public System.Collections.Generic.List<string> NomLocal
        {
            get
            {
                return this.NomLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomLocalField, value) != true))
                {
                    this.NomLocalField = value;
                    this.RaisePropertyChanged("NomLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<System.Nullable<System.DateTime>> DdLocal
        {
            get
            {
                return this.DdLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DdLocalField, value) != true))
                {
                    this.DdLocalField = value;
                    this.RaisePropertyChanged("DdLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public System.Collections.Generic.List<System.Nullable<System.DateTime>> DfLocal
        {
            get
            {
                return this.DfLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.DfLocalField, value) != true))
                {
                    this.DfLocalField = value;
                    this.RaisePropertyChanged("DfLocal");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public int NbrOcc
        {
            get
            {
                return this.NbrOccField;
            }
            set
            {
                if ((this.NbrOccField.Equals(value) != true))
                {
                    this.NbrOccField = value;
                    this.RaisePropertyChanged("NbrOcc");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnInfoTau", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnInfoTau : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private string CodTerriTauField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodTerriTau
        {
            get
            {
                return this.CodTerriTauField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriTauField, value) != true))
                {
                    this.CodTerriTauField = value;
                    this.RaisePropertyChanged("CodTerriTau");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnInfoTerriRLS", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnInfoTerriRLS : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CodTerriRLSField;

        private System.Collections.Generic.List<string> NomTerriRLSField;

        private System.Collections.Generic.List<string> CodRegnSocSanField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> CodTerriRLS
        {
            get
            {
                return this.CodTerriRLSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriRLSField, value) != true))
                {
                    this.CodTerriRLSField = value;
                    this.RaisePropertyChanged("CodTerriRLS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> NomTerriRLS
        {
            get
            {
                return this.NomTerriRLSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomTerriRLSField, value) != true))
                {
                    this.NomTerriRLSField = value;
                    this.RaisePropertyChanged("NomTerriRLS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<string> CodRegnSocSan
        {
            get
            {
                return this.CodRegnSocSanField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRegnSocSanField, value) != true))
                {
                    this.CodRegnSocSanField = value;
                    this.RaisePropertyChanged("CodRegnSocSan");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnInfoTerriCLSC", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnInfoTerriCLSC : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> CodTerriCLSCField;

        private System.Collections.Generic.List<string> NomTerriCLSCField;

        private System.Collections.Generic.List<string> CodRSSField;

        private System.Collections.Generic.List<string> CodRUISField;

        private System.Collections.Generic.List<string> CodRLSField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> CodTerriCLSC
        {
            get
            {
                return this.CodTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriCLSCField, value) != true))
                {
                    this.CodTerriCLSCField = value;
                    this.RaisePropertyChanged("CodTerriCLSC");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> NomTerriCLSC
        {
            get
            {
                return this.NomTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomTerriCLSCField, value) != true))
                {
                    this.NomTerriCLSCField = value;
                    this.RaisePropertyChanged("NomTerriCLSC");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<string> CodRSS
        {
            get
            {
                return this.CodRSSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRSSField, value) != true))
                {
                    this.CodRSSField = value;
                    this.RaisePropertyChanged("CodRSS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public System.Collections.Generic.List<string> CodRUIS
        {
            get
            {
                return this.CodRUISField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRUISField, value) != true))
                {
                    this.CodRUISField = value;
                    this.RaisePropertyChanged("CodRUIS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public System.Collections.Generic.List<string> CodRLS
        {
            get
            {
                return this.CodRLSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRLSField, value) != true))
                {
                    this.CodRLSField = value;
                    this.RaisePropertyChanged("CodRLS");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "SortieObtnNomLoc", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class SortieObtnNomLoc : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.ParamSorti
    {

        private string CodRetField;

        private System.Collections.Generic.List<string> LocCodField;

        private System.Collections.Generic.List<string> LocNomField;

        private System.Collections.Generic.List<string> LocDdField;

        private System.Collections.Generic.List<string> LocDfField;

        private System.Collections.Generic.List<string> NouvLocCodField;

        private System.Collections.Generic.List<string> NouvLocNomField;

        private System.Collections.Generic.List<string> NouvLocDdField;

        private System.Collections.Generic.List<string> NouvLocCodDfField;

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRet
        {
            get
            {
                return this.CodRetField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRetField, value) != true))
                {
                    this.CodRetField = value;
                    this.RaisePropertyChanged("CodRet");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> LocCod
        {
            get
            {
                return this.LocCodField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocCodField, value) != true))
                {
                    this.LocCodField = value;
                    this.RaisePropertyChanged("LocCod");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.Collections.Generic.List<string> LocNom
        {
            get
            {
                return this.LocNomField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocNomField, value) != true))
                {
                    this.LocNomField = value;
                    this.RaisePropertyChanged("LocNom");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public System.Collections.Generic.List<string> LocDd
        {
            get
            {
                return this.LocDdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocDdField, value) != true))
                {
                    this.LocDdField = value;
                    this.RaisePropertyChanged("LocDd");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public System.Collections.Generic.List<string> LocDf
        {
            get
            {
                return this.LocDfField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocDfField, value) != true))
                {
                    this.LocDfField = value;
                    this.RaisePropertyChanged("LocDf");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public System.Collections.Generic.List<string> NouvLocCod
        {
            get
            {
                return this.NouvLocCodField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NouvLocCodField, value) != true))
                {
                    this.NouvLocCodField = value;
                    this.RaisePropertyChanged("NouvLocCod");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public System.Collections.Generic.List<string> NouvLocNom
        {
            get
            {
                return this.NouvLocNomField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NouvLocNomField, value) != true))
                {
                    this.NouvLocNomField = value;
                    this.RaisePropertyChanged("NouvLocNom");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 7)]
        public System.Collections.Generic.List<string> NouvLocDd
        {
            get
            {
                return this.NouvLocDdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NouvLocDdField, value) != true))
                {
                    this.NouvLocDdField = value;
                    this.RaisePropertyChanged("NouvLocDd");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 8)]
        public System.Collections.Generic.List<string> NouvLocCodDf
        {
            get
            {
                return this.NouvLocCodDfField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NouvLocCodDfField, value) != true))
                {
                    this.NouvLocCodDfField = value;
                    this.RaisePropertyChanged("NouvLocCodDf");
                }
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MsgTrait", Namespace = "http://COD1_V4OutilBase_cpo/1")]
    [System.SerializableAttribute()]
    public partial class MsgTrait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodAppliField;

        private string IdMsgField;

        private string CodSeverField;

        private string TxtMsgFranField;

        private string TxtMsgAnglField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodAppli
        {
            get
            {
                return this.CodAppliField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodAppliField, value) != true))
                {
                    this.CodAppliField = value;
                    this.RaisePropertyChanged("CodAppli");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string IdMsg
        {
            get
            {
                return this.IdMsgField;
            }
            set
            {
                if ((object.ReferenceEquals(this.IdMsgField, value) != true))
                {
                    this.IdMsgField = value;
                    this.RaisePropertyChanged("IdMsg");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string CodSever
        {
            get
            {
                return this.CodSeverField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodSeverField, value) != true))
                {
                    this.CodSeverField = value;
                    this.RaisePropertyChanged("CodSever");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string TxtMsgFran
        {
            get
            {
                return this.TxtMsgFranField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TxtMsgFranField, value) != true))
                {
                    this.TxtMsgFranField = value;
                    this.RaisePropertyChanged("TxtMsgFran");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string TxtMsgAngl
        {
            get
            {
                return this.TxtMsgAnglField;
            }
            set
            {
                if ((object.ReferenceEquals(this.TxtMsgAnglField, value) != true))
                {
                    this.TxtMsgAnglField = value;
                    this.RaisePropertyChanged("TxtMsgAngl");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnInfoPays", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnInfoPays : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int CodPaysField;

        private string NomPaysFranField;

        private string NomAbrPaysFranField;

        private string NomPaysAnglField;

        private string NomAbrPaysAnglField;

        private string CodPaysCar2Field;

        private string CodPaysCar3Field;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int CodPays
        {
            get
            {
                return this.CodPaysField;
            }
            set
            {
                if ((this.CodPaysField.Equals(value) != true))
                {
                    this.CodPaysField = value;
                    this.RaisePropertyChanged("CodPays");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string NomPaysFran
        {
            get
            {
                return this.NomPaysFranField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPaysFranField, value) != true))
                {
                    this.NomPaysFranField = value;
                    this.RaisePropertyChanged("NomPaysFran");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string NomAbrPaysFran
        {
            get
            {
                return this.NomAbrPaysFranField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomAbrPaysFranField, value) != true))
                {
                    this.NomAbrPaysFranField = value;
                    this.RaisePropertyChanged("NomAbrPaysFran");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string NomPaysAngl
        {
            get
            {
                return this.NomPaysAnglField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPaysAnglField, value) != true))
                {
                    this.NomPaysAnglField = value;
                    this.RaisePropertyChanged("NomPaysAngl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string NomAbrPaysAngl
        {
            get
            {
                return this.NomAbrPaysAnglField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomAbrPaysAnglField, value) != true))
                {
                    this.NomAbrPaysAnglField = value;
                    this.RaisePropertyChanged("NomAbrPaysAngl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 5)]
        public string CodPaysCar2
        {
            get
            {
                return this.CodPaysCar2Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodPaysCar2Field, value) != true))
                {
                    this.CodPaysCar2Field = value;
                    this.RaisePropertyChanged("CodPaysCar2");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public string CodPaysCar3
        {
            get
            {
                return this.CodPaysCar3Field;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodPaysCar3Field, value) != true))
                {
                    this.CodPaysCar3Field = value;
                    this.RaisePropertyChanged("CodPaysCar3");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnTerriCLSCCP", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnTerriCLSCCP : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ListeCPField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ListeCP
        {
            get
            {
                return this.ListeCPField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListeCPField, value) != true))
                {
                    this.ListeCPField = value;
                    this.RaisePropertyChanged("ListeCP");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnTerriCLSCCodLocal", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnTerriCLSCCodLocal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ListeCodLocalField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ListeCodLocal
        {
            get
            {
                return this.ListeCodLocalField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListeCodLocalField, value) != true))
                {
                    this.ListeCodLocalField = value;
                    this.RaisePropertyChanged("ListeCodLocal");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnCodRSS", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnCodRSS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string ListeLocCodField;

        private System.DateTime DatTraitField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string ListeLocCod
        {
            get
            {
                return this.ListeLocCodField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ListeLocCodField, value) != true))
                {
                    this.ListeLocCodField = value;
                    this.RaisePropertyChanged("ListeLocCod");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.DateTime DatTrait
        {
            get
            {
                return this.DatTraitField;
            }
            set
            {
                if ((this.DatTraitField.Equals(value) != true))
                {
                    this.DatTraitField = value;
                    this.RaisePropertyChanged("DatTrait");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnInfoLocalPart", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnInfoLocalPart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string NomPartField;

        private System.DateTime DatServField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string NomPart
        {
            get
            {
                return this.NomPartField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NomPartField, value) != true))
                {
                    this.NomPartField = value;
                    this.RaisePropertyChanged("NomPart");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public System.DateTime DatServ
        {
            get
            {
                return this.DatServField;
            }
            set
            {
                if ((this.DatServField.Equals(value) != true))
                {
                    this.DatServField = value;
                    this.RaisePropertyChanged("DatServ");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnInfoTau", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnInfoTau : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string LocCodField;

        private int NoEntenField;

        private System.DateTime ServField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string LocCod
        {
            get
            {
                return this.LocCodField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LocCodField, value) != true))
                {
                    this.LocCodField = value;
                    this.RaisePropertyChanged("LocCod");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int NoEnten
        {
            get
            {
                return this.NoEntenField;
            }
            set
            {
                if ((this.NoEntenField.Equals(value) != true))
                {
                    this.NoEntenField = value;
                    this.RaisePropertyChanged("NoEnten");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public System.DateTime Serv
        {
            get
            {
                return this.ServField;
            }
            set
            {
                if ((this.ServField.Equals(value) != true))
                {
                    this.ServField = value;
                    this.RaisePropertyChanged("Serv");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnInfoTerriRLS", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnInfoTerriRLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CodRSSField;

        private string CodTerriRLSRechrField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodRSS
        {
            get
            {
                return this.CodRSSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodRSSField, value) != true))
                {
                    this.CodRSSField = value;
                    this.RaisePropertyChanged("CodRSS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string CodTerriRLSRechr
        {
            get
            {
                return this.CodTerriRLSRechrField;
            }
            set
            {
                if ((object.ReferenceEquals(this.CodTerriRLSRechrField, value) != true))
                {
                    this.CodTerriRLSRechrField = value;
                    this.RaisePropertyChanged("CodTerriRLSRechr");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "EntreObtnInfoTerriCLSC", Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1")]
    [System.SerializableAttribute()]
    public partial class EntreObtnInfoTerriCLSC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string strCodTerriCLSCField;

        private string strNomTerriCLSCField;

        private string strCodRSSField;

        private string strCodTerriRUISField;

        private string strCodTerriRLSField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string strCodTerriCLSC
        {
            get
            {
                return this.strCodTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.strCodTerriCLSCField, value) != true))
                {
                    this.strCodTerriCLSCField = value;
                    this.RaisePropertyChanged("strCodTerriCLSC");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string strNomTerriCLSC
        {
            get
            {
                return this.strNomTerriCLSCField;
            }
            set
            {
                if ((object.ReferenceEquals(this.strNomTerriCLSCField, value) != true))
                {
                    this.strNomTerriCLSCField = value;
                    this.RaisePropertyChanged("strNomTerriCLSC");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string strCodRSS
        {
            get
            {
                return this.strCodRSSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.strCodRSSField, value) != true))
                {
                    this.strCodRSSField = value;
                    this.RaisePropertyChanged("strCodRSS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 3)]
        public string strCodTerriRUIS
        {
            get
            {
                return this.strCodTerriRUISField;
            }
            set
            {
                if ((object.ReferenceEquals(this.strCodTerriRUISField, value) != true))
                {
                    this.strCodTerriRUISField = value;
                    this.RaisePropertyChanged("strCodTerriRUIS");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 4)]
        public string strCodTerriRLS
        {
            get
            {
                return this.strCodTerriRLSField;
            }
            set
            {
                if ((object.ReferenceEquals(this.strCodTerriRLSField, value) != true))
                {
                    this.strCodTerriRLSField = value;
                    this.RaisePropertyChanged("strCodTerriRLS");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1", ConfigurationName = "svcObtnInfoLocal.IServObtnInfoLocal")]
    public interface IServObtnInfoLocal
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirNom" +
            "Local", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirNom" +
            "LocalResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnNomLoc ObtenirNomLocal(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnNomLoc _objParamObtnNomLoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirNom" +
            "Local", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirNom" +
            "LocalResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnNomLoc> ObtenirNomLocalAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnNomLoc _objParamObtnNomLoc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oPays", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oPaysResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoPays ObtenirInfoPays(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoPays _objParamObtnInfoPays);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oPays", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oPaysResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoPays> ObtenirInfoPaysAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoPays _objParamObtnInfoPays);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCP", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCPResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCP ObtenirTerriCLSCCP(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCP _objParamObtnTerriCLSCCP);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCP", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCPResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCP> ObtenirTerriCLSCCPAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCP _objParamObtnTerriCLSCCP);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCodLocal", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCodLocalResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCodLocal ObtenirTerriCLSCCodLocal(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCodLocal _objParamObtnTerriCLSCCodLocal);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCodLocal", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirTer" +
            "riCLSCCodLocalResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCodLocal> ObtenirTerriCLSCCodLocalAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCodLocal _objParamObtnTerriCLSCCodLocal);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirCod" +
            "RSS", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirCod" +
            "RSSResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnCodRSS ObtenirCodRSS(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnCodRSS _objParamObtnCodRSS);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirCod" +
            "RSS", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirCod" +
            "RSSResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnCodRSS> ObtenirCodRSSAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnCodRSS _objParamObtnCodRSS);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oLocalPart", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oLocalPartResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoLocalPart ObtenirInfoLocalPart(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoLocalPart _objObtnInfoLocalPart);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oLocalPart", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oLocalPartResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoLocalPart> ObtenirInfoLocalPartAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoLocalPart _objObtnInfoLocalPart);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTau", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTauResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTau ObtenirInfoTau(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTau _objObtnInfoTau);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTau", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTauResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTau> ObtenirInfoTauAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTau _objObtnInfoTau);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriRLS", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriRLSResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriRLS ObtenirInfoTerriRLS(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriRLS _objObtnInfoTerriRLS);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriRLS", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriRLSResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriRLS> ObtenirInfoTerriRLSAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriRLS _objObtnInfoTerriRLS);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriCLSC", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriCLSCResponse")]
        RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriCLSC ObtenirInfoTerriCLSC(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriCLSC _objObtnInfoTerriCLSC);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriCLSC", ReplyAction = "http://www.ramq.gouv.qc.ca/SOB2_ObtnInfoLocal_svc/1/IServObtnInfoLocal/ObtenirInf" +
            "oTerriCLSCResponse")]
        System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriCLSC> ObtenirInfoTerriCLSCAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriCLSC _objObtnInfoTerriCLSC);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServObtnInfoLocalChannel : RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.IServObtnInfoLocal, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServObtnInfoLocalClient : RAMQ.ServiceModel.ClientBaseRAMQ<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.IServObtnInfoLocal>, RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.IServObtnInfoLocal
    {

        public ServObtnInfoLocalClient()
        {
        }

        public ServObtnInfoLocalClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ServObtnInfoLocalClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServObtnInfoLocalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ServObtnInfoLocalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnNomLoc ObtenirNomLocal(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnNomLoc _objParamObtnNomLoc)
        {
            return base.Channel.ObtenirNomLocal(_objParamObtnNomLoc);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnNomLoc> ObtenirNomLocalAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnNomLoc _objParamObtnNomLoc)
        {
            return base.Channel.ObtenirNomLocalAsync(_objParamObtnNomLoc);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoPays ObtenirInfoPays(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoPays _objParamObtnInfoPays)
        {
            return base.Channel.ObtenirInfoPays(_objParamObtnInfoPays);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoPays> ObtenirInfoPaysAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoPays _objParamObtnInfoPays)
        {
            return base.Channel.ObtenirInfoPaysAsync(_objParamObtnInfoPays);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCP ObtenirTerriCLSCCP(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCP _objParamObtnTerriCLSCCP)
        {
            return base.Channel.ObtenirTerriCLSCCP(_objParamObtnTerriCLSCCP);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCP> ObtenirTerriCLSCCPAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCP _objParamObtnTerriCLSCCP)
        {
            return base.Channel.ObtenirTerriCLSCCPAsync(_objParamObtnTerriCLSCCP);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCodLocal ObtenirTerriCLSCCodLocal(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCodLocal _objParamObtnTerriCLSCCodLocal)
        {
            return base.Channel.ObtenirTerriCLSCCodLocal(_objParamObtnTerriCLSCCodLocal);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnTerriCLSCCodLocal> ObtenirTerriCLSCCodLocalAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnTerriCLSCCodLocal _objParamObtnTerriCLSCCodLocal)
        {
            return base.Channel.ObtenirTerriCLSCCodLocalAsync(_objParamObtnTerriCLSCCodLocal);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnCodRSS ObtenirCodRSS(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnCodRSS _objParamObtnCodRSS)
        {
            return base.Channel.ObtenirCodRSS(_objParamObtnCodRSS);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnCodRSS> ObtenirCodRSSAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnCodRSS _objParamObtnCodRSS)
        {
            return base.Channel.ObtenirCodRSSAsync(_objParamObtnCodRSS);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoLocalPart ObtenirInfoLocalPart(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoLocalPart _objObtnInfoLocalPart)
        {
            return base.Channel.ObtenirInfoLocalPart(_objObtnInfoLocalPart);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoLocalPart> ObtenirInfoLocalPartAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoLocalPart _objObtnInfoLocalPart)
        {
            return base.Channel.ObtenirInfoLocalPartAsync(_objObtnInfoLocalPart);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTau ObtenirInfoTau(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTau _objObtnInfoTau)
        {
            return base.Channel.ObtenirInfoTau(_objObtnInfoTau);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTau> ObtenirInfoTauAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTau _objObtnInfoTau)
        {
            return base.Channel.ObtenirInfoTauAsync(_objObtnInfoTau);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriRLS ObtenirInfoTerriRLS(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriRLS _objObtnInfoTerriRLS)
        {
            return base.Channel.ObtenirInfoTerriRLS(_objObtnInfoTerriRLS);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriRLS> ObtenirInfoTerriRLSAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriRLS _objObtnInfoTerriRLS)
        {
            return base.Channel.ObtenirInfoTerriRLSAsync(_objObtnInfoTerriRLS);
        }

        public RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriCLSC ObtenirInfoTerriCLSC(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriCLSC _objObtnInfoTerriCLSC)
        {
            return base.Channel.ObtenirInfoTerriCLSC(_objObtnInfoTerriCLSC);
        }

        public System.Threading.Tasks.Task<RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.SortieObtnInfoTerriCLSC> ObtenirInfoTerriCLSCAsync(RAMQ.PRE.PRE_SysExt_cpo.svcObtnInfoLocal.EntreObtnInfoTerriCLSC _objObtnInfoTerriCLSC)
        {
            return base.Channel.ObtenirInfoTerriCLSCAsync(_objObtnInfoTerriCLSC);
        }
    }
}
